name = "teledirectmd-router"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
VERCEL_ORIGIN = "https://teledirectmd-pages.vercel.app"
SQUARESPACE_ORIGIN = "https://teledirectmd.squarespace.com"
VERIFY_ORIGIN = "https://teledirectmd-verify.vercel.app"
